(ns reefer.db)

(def default-db
  {:varnames {:t "Temp"
              :p "Pressure"
              :h "Humidity"
              :w "Wind"}
   :selvar :w
   :capitals {1 "Rome,IT"
              2 "Paris,FR"
              3 "Berlin,DE"
              4 "London,UK"
              5 "Brussels,BE"
              6 "Amsterdam,NL"
              7 "Geneva,CH"
              8 "Prague,CZ"
              9 "Warsaw,PL"
              10 "Moscow,RU"
              11 "Copenhagen,DK"
              12 "Stockholm,SE"
              13 "Madrid,ES"}
   :italy {1 "Rome,IT"
           2 "Venice,IT"
           3 "Milan,IT"
           4 "Florence,IT"
           5 "Turin,IT"
           6 "Naples,IT"
           7 "Palermo,IT"
           8 "Genoa,IT"}
   :france {1 "Paris,FR"
            2 "Lyon,FR"
            3 "Marseille,FR"
            4 "Bordeaux,FR"
            5 "Lille,FR"
            6 "Strasbourg,FR"
            7 "Montpellier,FR"
            8 "Nice,FR"
            9 "Nantes,FR"
            10 "Brest,FR"}
   :germany {1 "Berlin,DE"
             2 "Frankfurt,DE"
             3 "Cologne,DE"
             4 "Stuttgart,DE"
             5 "Munich,DE"
             6 "Bonn,DE"
             7 "Dresden,DE"
             8 "Hamburg,DE"}
   :us {1 "Boston"
        2 "New York"
        3 "Chicago"
        4 "Los Angeles"
        5 "San Francisco"
        6 "New Orleans"
        7 "Washington"
        8 "Denver"
        9 "Seattle"
        10 "Dallas"
        11 "Houston"
        12 "Denver"
        13 "Salt Lake City"
        14 "Minneapolis"
        15 "Charlotte"}
   :uk {1 "London,UK"
        2 "Manchester,UK"
        3 "Birmingham,UK"
        4 "Edinburgh,UK"
        5 "Bristol,UK"
        6 "Dublin,IE"
        7 "Cambridge,UK"
        8 "Oxford,UK"}})
